/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AddressUpdateManyWithoutCompaniesInput } from "./AddressUpdateManyWithoutCompaniesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ContactUpdateManyWithoutCompaniesInput } from "./ContactUpdateManyWithoutCompaniesInput";
import { DeviceUpdateManyWithoutCompaniesInput } from "./DeviceUpdateManyWithoutCompaniesInput";
import { UserUpdateManyWithoutCompaniesInput } from "./UserUpdateManyWithoutCompaniesInput";
@InputType()
class CompanyUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AddressUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => AddressUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => AddressUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  addresses?: AddressUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: () => ContactUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => ContactUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => ContactUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  contacts?: ContactUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: () => DeviceUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => DeviceUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => DeviceUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  devices?: DeviceUpdateManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  document?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  logo?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutCompaniesInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutCompaniesInput;
}
export { CompanyUpdateInput };
