/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeviceService } from "../device.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeviceCreateInput } from "./DeviceCreateInput";
import { DeviceWhereInput } from "./DeviceWhereInput";
import { DeviceWhereUniqueInput } from "./DeviceWhereUniqueInput";
import { DeviceFindManyArgs } from "./DeviceFindManyArgs";
import { DeviceUpdateInput } from "./DeviceUpdateInput";
import { Device } from "./Device";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeviceControllerBase {
  constructor(
    protected readonly service: DeviceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Device })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: DeviceCreateInput): Promise<Device> {
    return await this.service.create({
      data: {
        ...data,

        company: data.company
          ? {
              connect: data.company,
            }
          : undefined,

        group: data.group
          ? {
              connect: data.group,
            }
          : undefined,
      },
      select: {
        activateDate: true,
        advancedConfig: true,

        company: {
          select: {
            id: true,
          },
        },

        config: true,
        createdAt: true,
        expireDate: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        kind: true,
        name: true,
        tags: true,
        updatedAt: true,
        uuid: true,
        version: true,
        worktime: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Device] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(DeviceFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Device[]> {
    const args = plainToClass(DeviceFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        activateDate: true,
        advancedConfig: true,

        company: {
          select: {
            id: true,
          },
        },

        config: true,
        createdAt: true,
        expireDate: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        kind: true,
        name: true,
        tags: true,
        updatedAt: true,
        uuid: true,
        version: true,
        worktime: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: DeviceWhereUniqueInput
  ): Promise<Device | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        activateDate: true,
        advancedConfig: true,

        company: {
          select: {
            id: true,
          },
        },

        config: true,
        createdAt: true,
        expireDate: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        kind: true,
        name: true,
        tags: true,
        updatedAt: true,
        uuid: true,
        version: true,
        worktime: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() data: DeviceUpdateInput
  ): Promise<Device | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          company: data.company
            ? {
                connect: data.company,
              }
            : undefined,

          group: data.group
            ? {
                connect: data.group,
              }
            : undefined,
        },
        select: {
          activateDate: true,
          advancedConfig: true,

          company: {
            select: {
              id: true,
            },
          },

          config: true,
          createdAt: true,
          expireDate: true,

          group: {
            select: {
              id: true,
            },
          },

          id: true,
          isActive: true,
          kind: true,
          name: true,
          tags: true,
          updatedAt: true,
          uuid: true,
          version: true,
          worktime: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: DeviceWhereUniqueInput
  ): Promise<Device | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          activateDate: true,
          advancedConfig: true,

          company: {
            select: {
              id: true,
            },
          },

          config: true,
          createdAt: true,
          expireDate: true,

          group: {
            select: {
              id: true,
            },
          },

          id: true,
          isActive: true,
          kind: true,
          name: true,
          tags: true,
          updatedAt: true,
          uuid: true,
          version: true,
          worktime: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
